FROM golang:alpine

# important!
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
ENV GOFLAGS=-mod=vendor
ENV APP_USER app
ENV APP_HOME /go/src/github.com/krassor/serverHttp

#RUN mkdir ${APP_HOME}
WORKDIR ${APP_HOME}
RUN cd ${APP_HOME}
ADD . ${APP_HOME}


#compile your project
RUN go mod vendor
RUN go build -o bin/app-serverHttp app/main.go

#open the port 8000
EXPOSE 8001
CMD [ ${APP_HOME}"/bin/app-serverHttp" ]